// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uzccqsaiqeqcgcueeonh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV6Y2Nxc2FpcWVxY2djdWVlb25oIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ4NDY1NjksImV4cCI6MjA3MDQyMjU2OX0.vdhnAc4nUpyM-KZyvBunVHMlR55fozGACfzM1th-EWU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});